# An example of one time (one iteration) crossover and mutation on population used in Genetic Algorithm

In [65]:
import numpy as np

pop_size = 10
mutation_rate = 0.3
crossover_rate = 0.7
num_variables = 2
lower_bound = -5
upper_bound = +5

population = np.random.uniform(low=lower_bound, high=upper_bound, size=(pop_size, num_variables))

# fitness value for each individual (or chromosome OR a set of decision variables) must be computed by the objective funtion
# but here to just simpilify we assign a random number for each individual
fitness = np.random.uniform(low=0, high=10, size=(pop_size, 1))

print("Population:\n",population)
print("\nAssume these are the values computed by objective function for each individual:\n",fitness)


Population:
 [[ 2.71843488 -2.85949323]
 [-4.51151096  1.47779656]
 [ 2.21579661 -2.64756011]
 [ 4.03548186  4.8548216 ]
 [-4.87559991 -1.31490033]
 [-0.93056034 -2.27400797]
 [-4.0896798  -1.01587917]
 [ 1.35890518 -1.51876773]
 [ 0.99579887 -4.70993681]
 [-2.62933684 -4.59017213]]

Assume these are the values computed by objective function for each individual:
 [[8.70695161]
 [5.59897383]
 [5.20525816]
 [7.11696937]
 [4.53519688]
 [3.02007389]
 [0.18130754]
 [0.22837139]
 [3.69808229]
 [6.54423847]]


We want to minimize the objective function. So the more fitness values is, the less possibility it has to be the solution. That's why I do inverse of fitness. Deviding by `+1e-6` is to make sure we won't have division by zero.

In [66]:
fitness_probs = 1 / (fitness + 1e-6)  # Adding a small constant to avoid division by zero

# Normalize the probabilities
fitness_probs /= fitness_probs.sum()

print("The probility of individuals:\n",fitness_probs)
# print("Sum of probabilities:",fitness_probs.sum())

The probility of individuals:
 [[0.00999121]
 [0.0155373 ]
 [0.01671251]
 [0.01222331]
 [0.01918174]
 [0.0288049 ]
 [0.47980623]
 [0.38092594]
 [0.0235238 ]
 [0.01329306]]


I use `np.random.choice` function to pick the stronger individuals (the ones with higher probability are more likely to survive, althogh, there is a slight chance that individuals with less probability are going to survive too).

In [67]:
# Select parents to crossover based on their probabilities
selected_indices = np.random.choice(pop_size, size=pop_size, p=fitness_probs[:, 0])

# Create the new population with selected parents
new_population = population[selected_indices, :]

print("The index of individuals (chromosomes) that survived:\n",selected_indices)

The index of individuals (chromosomes) that survived:
 [7 6 6 6 7 5 7 6 7 7]


**IMPORTANT:** Every time you run this part a new set of indexes will be picked. But the ones you see more frequently are those which have higher probability in `fitness_probs`. Then I created `new_population` based on `selected_indices` holding the individuals with higher probability to be the best solution. And these survived individuals are going to make children and mutate to make the next generation!

In [68]:
print("New population:\n",new_population)

New population:
 [[ 1.35890518 -1.51876773]
 [-4.0896798  -1.01587917]
 [-4.0896798  -1.01587917]
 [-4.0896798  -1.01587917]
 [ 1.35890518 -1.51876773]
 [-0.93056034 -2.27400797]
 [ 1.35890518 -1.51876773]
 [-4.0896798  -1.01587917]
 [ 1.35890518 -1.51876773]
 [ 1.35890518 -1.51876773]]


Here, every two parents in `new_population` will make two new kids! carrying the same gens that their parents had. Mind you that there is a `crossover_rate` percent chance that two parents would be able to mate. Others will remain untouched. They stay single or you can say they don't want to be in a serious relationship!

In [76]:
# Perform crossover
for i in range(0, pop_size, 2):
    if np.random.rand() < crossover_rate:
        parent1 = new_population[i]
        parent2 = new_population[i + 1]

        # Pick a random crossover point
        crosspoint = np.random.randint(1, num_variables) # always 1 for 2 variables

        # Create two new children
        child1 = np.concatenate((parent1[:crosspoint], parent2[crosspoint:]))
        child2 = np.concatenate((parent2[:crosspoint], parent1[crosspoint:]))

        # Replace the parents with the new children
        new_population[i] = child1
        new_population[i + 1] = child2


1
1
2
2
1
2
2
1
1
1
1
1
2
2
2
2
2
2
2
2
1
2
2
2
2
1
2
2
1
2
1
1
2
2
2
2
2
1
2
2
2
2
1
2
1
1
2
2
2
1
2
2
1
1
1
2
2
1
1
2
1
1
1
1
2
2
2
2
1
1
1
2
2
1
2
1
2
1
1
1
2
1
2
1
2
2
2
2
2
1
1
2
1
2
2
1
1
1
1


IndexError: index 99 is out of bounds for axis 0 with size 10

Now the new population is like:

In [70]:
new_population

array([[ 1.35890518, -1.01587917],
       [-4.0896798 , -1.51876773],
       [-4.0896798 , -1.01587917],
       [-4.0896798 , -1.01587917],
       [ 1.35890518, -1.51876773],
       [-0.93056034, -2.27400797],
       [ 1.35890518, -1.01587917],
       [-4.0896798 , -1.51876773],
       [ 1.35890518, -1.51876773],
       [ 1.35890518, -1.51876773]])

The survived ones will have the chance to also mutate. Here is the story. Some say that Tyrannosaurus rex especies extincted because they had short hands and couldn't grab the food on the ground! "Some" also say Segnosaurus survived because there was enough food for them but they mutated to develop longer hands and eventually during millions of years (iterations in GA) they turned into monekys. This is not a real story I just made it up!

Anyway, the total number of individuals (or chromosomes) are equal to `pop_size`. The total number of gens in each population holding are chromosomes are `pop_size * num_variables`. And randomly `mutation_rate` percent of them will mutate.

In [71]:
# Calculate the total number of genes
total_gen = pop_size * num_variables

# Calculate the number of genes to mutate
total_gen_mutate = int(total_gen * mutation_rate)

# Generate random indices for genes to mutate
genes_to_mutate_indices = np.random.choice(total_gen, size=total_gen_mutate, replace=False)

print("Total numebr of gens: \n",total_gen)
print("\nTotal number of gens that will randomly mutate: \n",total_gen_mutate)
print("\nThe indexes of gens that will be mutate (numbers between zero to total_gen): \n",genes_to_mutate_indices)


Total numebr of gens: 
 20

Total number of gens that will randomly mutate: 
 6

The indexes of gens that will be mutate (numbers between zero to total_gen): 
 [ 4  8  5 13 10 15]


Here the gens that will mutate are replaced with a random number between lower_bound and upper_bound. These are the bounds for the decision variables (gens).

In [72]:
# Mutate the selected genes
for index in genes_to_mutate_indices:
    row = index // num_variables
    col = index % num_variables
    print(row, col)
    new_population[row, col] = np.random.uniform(low=lower_bound, high=upper_bound)
print(new_population)

2 0
4 0
2 1
6 1
5 0
7 1
[[ 1.35890518 -1.01587917]
 [-4.0896798  -1.51876773]
 [ 0.96226013 -4.14421447]
 [-4.0896798  -1.01587917]
 [-2.73752195 -1.51876773]
 [-3.24940115 -2.27400797]
 [ 1.35890518  1.83320581]
 [-4.0896798   0.64290969]
 [ 1.35890518 -1.51876773]
 [ 1.35890518 -1.51876773]]


Now this a new update generation. I recompute the fitness with objective function and the probability of each indiviudal for this new population. I will keep do this until I get enough accuracy.

In [73]:
new_population

array([[ 1.35890518, -1.01587917],
       [-4.0896798 , -1.51876773],
       [ 0.96226013, -4.14421447],
       [-4.0896798 , -1.01587917],
       [-2.73752195, -1.51876773],
       [-3.24940115, -2.27400797],
       [ 1.35890518,  1.83320581],
       [-4.0896798 ,  0.64290969],
       [ 1.35890518, -1.51876773],
       [ 1.35890518, -1.51876773]])

If you wanna see another numerical example you can read:
https://arxiv.org/pdf/1308.4675.pdf